### ISSUE TITLE
add pages

### ISSUE THREAD

**Issue by teryfly** [FHIR/sample-ig#37]
I'm trying to add some pages by add *.md files to the sample-ig\input\pagecontent dir, and add <page> tag in the ig.ini like this:
<page>
<nameUrl value="profliles.html"/>
<title value="my profiles list"/>
<generation value="markdown"/>
</page>
but I'm get the following err:
"Publishing Content Failed: Template based HTML file profliles.html is missing source file profliles.md "

How to add the "Template based HTML file profliles.html" to publish a new page?

**Comment by lmckenzi** [comment]
Can you share your whole `<page/>` entry for one of your .md files?

**Comment by teryfly** [comment]
<page>
      <nameUrl value="toc.html"/>
      <title value="目录"/>
      <generation value="html"/>
      <page>
        <nameUrl value="index.html"/>
        <title value="首页"/>
        <generation value="html"/>
      </page>
      <page>
        <nameUrl value="background.html"/>
        <title value="Background"/>
        <generation value="html"/>
      </page>
      <page>
        <nameUrl value="spec.html"/>
        <title value="核心规范"/>
        <generation value="markdown"/>
      </page>
	    
	  <page>
        <nameUrl value="profliles.html"/>
        <title value="资源结构与扩展"/>
        <generation value="markdown"/>
	  </page>
     
	
      <page>
        <nameUrl value="downloads.html"/>
        <title value="下载"/>
        <generation value="html"/>
      </page>
      <page>
        <nameUrl value="changes.html"/>
        <title value="指南历史版本"/>
        <generation value="html"/>
      </page>
    </page>

**Comment by teryfly** [comment]
This is the <page/> entry  in my ig.xml which is referenced in the ig.ini:
`  <page>`
       ` <nameUrl value="profliles.html"/>`
       ` <title value="my profiles list"/>`
        `<generation value="markdown"/>`
  `</page>`

and in the sample-ig\input\pagecontent\profliles.md is like this:

`{% include list-simple-profiles.xhtml %}`
`{% include list-simple-extensions.xhtml %}`

**Comment by lmckenzi** [comment]
It looks like there's a typo in nameUrl?  I suspect the file name in your input/pagecontent is named "profiles.md" rather than "profliles.md"

**Comment by teryfly** [comment]
thanks, I should concentrated!
