### ISSUE TITLE
Should input-cache be added to .gitignore?

### ISSUE THREAD

**Issue by lmsurpre** [FHIR/sample-ig#4]
I checked out the project and built it with IG Publisher.  Now it says I have uncommitted changes:
```
	modified:   input-cache/txcache/http___unstats.un.org_unsd_methods_m49_m49.htm.cache
	modified:   input-cache/txcache/loinc.cache
	modified:   input-cache/txcache/version.ctl
```

Do these need to be there on a fresh checkout?  How often do they change?

**Comment by lmckenzi** [comment]
You will want to commit all of the txcache stuff.  It speeds your build and also reduces load on the terminology server.  You may want to wipe it occasionally before doing an important build e.g. pre-publication.
