### ISSUE TITLE
Response 500 when adding webhook

### ISSUE THREAD

**Issue by njw-bupt** [FHIR/sample-ig#46]
Hi~
After adding webhook according to the readme, an error with code 500 was returned.
How to solve this issues?

![image](https://user-images.githubusercontent.com/29836250/115371788-ddcd9380-a1fc-11eb-8074-8371554aa695.png)

**Comment by lmckenzi** [comment]
What webhook and what readme are you referring to?

**Comment by njw-bupt** [comment]
> What webhook and what readme are you referring to?

I referred to cibuild.txt in classnotes
webhook:  https://us-central1-fhir-org-starter-project.cloudfunctions.net/ig-commit-trigger

**Comment by lmckenzi** [comment]
Is your Git project public?  Did you set up the Webhook to use JSON?

**Comment by njw-bupt** [comment]
Yes, it is a public repository. And I set the content-type to application/json.

**Comment by costateixeira** [comment]
Did you make a commit after setting up the webhook? If not, can you do so?
I believe the first response after you setup the webhook is this eror, but once you from the first commit or Pull Request on the **master** branch the subsquent responses are ok.
Just in case, this is the working configuration of the webhook
![image](https://user-images.githubusercontent.com/16153168/115896641-ee2f7980-a45b-11eb-9974-b27bcd576570.png)

**Comment by njw-bupt** [comment]
It works!
Thank you very much!
