### ISSUE TITLE
Missing jekyll

### ISSUE THREAD

**Issue by yunwwang** [FHIR/sample-ig#9]
When I run _genonce.sh, I got this error:
java.io.IOException: Cannot run program "jekyll" (in directory "/GitHub/sample-ig/temp/pages"): error=2, No such file or directory
Do I need to install it separately?

**Comment by grahamegrieve** [comment]
yes you need to install it as a pre-requisite

**Comment by steveswinsburg** [comment]
This issue is one of the top hits for this error so woiuld be helpful to add the instructions - the instructions for installing jekyll are here https://jekyllrb.com/docs/installation/
